name: RBAC Tests (dev-test)

on:
  workflow_dispatch:

jobs:
  rbac-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Run RBAC Tests
        run: mvn clean test -DsuiteXmlFile=src/test/resources/suites/testng-rbac.xml -Dtc.env=dev-test

      - name: Install Allure
        run: npm install -g allure-commandline --save-dev

      - name: Generate Allure Report
        if: always()
        run: |
          allure generate target/allure-results --clean -o allure-report
          touch allure-report/.nojekyll

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
          destination_dir: allure-rbac
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"

      - name: Add Allure Report URL to summary
        if: always()
        run: |
          echo "### ✅ Allure RBAC report published successfully!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "🔗 [Open Allure RBAC Report](https://irynadim.github.io/TeamConnect-API-TF/allure-rbac/)" >> $GITHUB_STEP_SUMMARY
